# -*- coding: utf-8 -*-
"""sa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khBCHkjJ8FtLcm58vGZsmoBJ0HNfXH6_
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install langdetect

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re
import string
import nltk
from nltk.stem import WordNetLemmatizer
from langdetect import detect

lemmatizer=WordNetLemmatizer()
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

df = pd.read_csv('pubg reviews.csv')
df.head()

df.describe()

df = df.drop(columns=['userName', 'appVersion','at'])
df.head()

pubg_review = df['content']
txt = list(pubg_review)

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt_tab')
stop_words = set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

txt_clean = []
for i in range(len(txt)):
    txt[i] = re.sub(r'\d+', '', txt[i]) # remove numbers
    txt[i] = txt[i].lower()     # lower case
    txt[i] = txt[i].translate(str.maketrans('', '', string.punctuation)) # remove punctuation
    txt[i] = txt[i].strip() # remove white space
    tokens = word_tokenize(txt[i]) # tokenize
    remove_stop = [lemmatizer.lemmatize(i) for i in tokens if not i in stop_words] # remove stop words and lemmatize
    txt_clean.append(' '.join(remove_stop))

!pip install wordcloud

df['label'] = df['score'].apply(
    lambda x: 'positive' if x in [4,5]
    else ('negative' if x in [1,2]
    else ('neutral' if x == 3
    else None))
)

df = df[df['label'].notna()]

from wordcloud import WordCloud
from wordcloud import STOPWORDS
stopwords = set(STOPWORDS)
stopwords.update(["game", 'PUBG','mobile','phone'])
from wordcloud import WordCloud, STOPWORDS

df_pos = df[df['label'] == 'positive']
textt = " ".join(review for review in df_pos['content'])
wordcloud = WordCloud(stopwords=stopwords).generate(text=textt)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")

"""The top 5 words in the positive review wordcloud are good, love, nice, best, and play."""

df_neg = df[df['label'] == 'negative']
textt = " ".join(review for review in df_neg['content'])
wordcloud = WordCloud(stopwords=stopwords).generate(text=textt)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")

"""The top 5 words in the negative reviews are update, play, please, good, and bad."""

df_neu = df[df['label'] == 'neutral']
textt = " ".join(review for review in df_neu['content'])
wordcloud = WordCloud(stopwords=stopwords).generate(text=textt)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")

"""The top 5 words in the neutral reviews are please, good, update, play, and time."""

nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer as SIA
sia = SIA()

score = [sia.polarity_scores(line) for line in txt_clean]
sentiment_df = pd.DataFrame.from_records(score)
sentiment_df.head()

import seaborn as sns

sns.kdeplot(sentiment_df['pos'], shade=True)
sns.kdeplot(sentiment_df['neg'], shade=True)
plt.legend(['pos', 'neg'])
plt.xlabel('Sentiment Score')
plt.show()

""" The positive distribution is spread out across the sentiment score, suggesting that positive reviews ranges from slightly positive to very positive.

 The negative distribution is narrow around 0, suggesting that most of the negative reviews are just slighly negative, possibly due to having a mixture of both positive and negative sentiment words.
"""

sentiment_df['text'] = txt_clean
negative = sentiment_df.iloc[sentiment_df.neg.nlargest(10).index]
positive = sentiment_df.iloc[sentiment_df.pos.nlargest(10).index]
print(f'Most negative:', list(negative.text))
print(f'Most positive:',  list(positive.text))

!pip install umap-learn
!pip install bertopic

from umap import UMAP # Dimension reduction # pip install umap-learn
from bertopic import BERTopic # pip install bertopic

umap_model = UMAP(n_neighbors=20, random_state=100)

topic_model = BERTopic(nr_topics='auto', verbose=True, umap_model=umap_model, calculate_probabilities=True, top_n_words=20)
topics, probs = topic_model.fit_transform(txt_clean)

topic_model.get_topic_info().head(12)

topic_model.visualize_barchart(top_n_topics=10)

"""Topic 0 is about positive overall gameplay experience.

Topic 1 is about nostalgic attachment to PUBG and long-term fan experiences.

Topic 2 is about general praise of the app's performance and usability.

Topic 3 is in a foreign language and is likely about network issues during gameplay.

Topic 4 is also in another foreign language and contains mostly noise and does not seem to represent any interpretable theme.

Topic 5 is about highly satisfied players giving superlative praise for the game.

Topic 6 is about appreciation and praise for the developers.

Topic 7 is about players feeling a emotional connections with the game.

Topic 8 is about players requesting free in-game currency.

Topic 9 is about account-related issues, such as hacking, login problems, and bans.
"""

df['topic'] = topics
df.groupby(['score','topic']).size().reset_index().sort_values(0, ascending=False)

topic_counts_1 = df[df['score']==1]['topic'].value_counts().head(5)
print(topic_counts_1)

"""The top topics discuss by 1 star reviewers are 1,3,9, and 4."""

topic_model.get_topic(3)

topic_counts_1 = df[df['score']==2]['topic'].value_counts().head(5)
print(topic_counts_1)

"""The top topics discuss by 2 star reviewers are 3,1,9,and 4."""

topic_model.get_topic(0)

topic_counts_1 = df[df['score']==3]['topic'].value_counts().head(5)
print(topic_counts_1)

"""The top topics discuss by 3 star reviewers are 1,0,3, and 4."""

topic_model.get_topic(1)

topic_counts_1 = df[df['score']==4]['topic'].value_counts().head(5)
print(topic_counts_1)

"""The top topics discuss by 4 star reviewers are 0,1,2, and 3."""

topic_model.get_topic(0)

topic_counts_1 = df[df['score']==5]['topic'].value_counts().head(5)
print(topic_counts_1)

"""The top topics discuss by 5 star reviewers are 0,1,2, and 5."""

topic_model.get_topic(0)

"""
Insights & Recomendations:

Most users have a positive view of the game, while the negative reviews tend to be only slightly negative.

Many of the negative reviews are about users preferring the older version of PUBG and reporting network or account issues. Addressing these issues shows where things can be improved.

"""